### ISSUE TITLE
does not start after saving settings

### ISSUE THREAD

**Issue by seoeaa** [mrvautin/expressCart#32]
in the admin panel
just save the settings as the script crashes and no longer starts until you restore the default file

settings.json incorrect: data should NOT have additional properties
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! express-cart@1.1.10 start: `node app.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the express-cart@1.1.10 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\34\AppData\Roaming\npm-cache\_logs\2018-10-11T22_53_12_748Z-debug.log

these lines break everything in the original file

    "env": ".min",
    "themeViews": "../views/themes/Cloth/"

**Comment by ealvizouri** [comment]
Hey, you must set additionalProperties to true in config/baseSchema.json, as it is specified in [ajv documentation](https://github.com/epoberezkin/ajv/blob/master/FAQ.md)

hope this helps!

----------
Those 2 lines must be deleted because those properties are set in getConfig function on lib/common.js
